import "./globals.css";
import "./custom-scroll.css";

export const metadata = {
  title: "Twitter Clone",
  description: "Generated by Afifudin Maarif",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen mx-auto lg:w-[375px] bg-white overflow-hidden">
        {children}
      </body>
    </html>
  );
}
